version: 0.2

phases:
  build:
    commands:
      - export NODE_ENV=production
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: asteroids-$(date +%Y-%m-%d)

