version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  build:
    commands:
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: asteroids-$(date +%Y-%m-%d)

